insert into categories(name,slug) values('Hasil Pertanian','hasil-pertanian'),('Benih & Bibit','benih-bibit'),('Pupuk','pupuk'),('Produk Pengendalian Hama','pengendalian-hama'),('Alat Pertanian','alat-pertanian'),('Mesin Pertanian','mesin-pertanian'),('Produk Olahan Pertanian','produk-olahan'),('Kebutuhan Pertanian Lainnya','lainnya');
insert into stores(store_name,slug,description,location) values('Tani Makmur Bogor','tani-makmur','Hasil panen segar','Bogor'),('Sukabumi Agro','sukabumi-agro','Sarana produksi','Sukabumi'),('Cianjur Jaya Tani','cianjur-jaya','Beras dan olahan','Cianjur');
with p(n,s,c,st,pr,u,l) as (values
('Beras Premium 5 kg','beras-premium','hasil-pertanian','cianjur-jaya',72000,'karung','Cianjur'),('Jagung Pipil','jagung-pipil','hasil-pertanian','tani-makmur',6500,'kg','Bogor'),('Cabai Merah','cabai-merah','hasil-pertanian','tani-makmur',45000,'kg','Bogor'),('Tomat','tomat','hasil-pertanian','tani-makmur',12000,'kg','Bogor'),('Bawang Merah','bawang-merah','hasil-pertanian','sukabumi-agro',32000,'kg','Sukabumi'),
('Benih Jagung Hibrida','benih-jagung','benih-bibit','sukabumi-agro',85000,'kemasan','Sukabumi'),('Benih Cabai','benih-cabai','benih-bibit','sukabumi-agro',25000,'kemasan','Sukabumi'),('Benih Padi','benih-padi','benih-bibit','cianjur-jaya',60000,'kemasan','Cianjur'),
('Pupuk Urea 50 kg','pupuk-urea','pupuk','sukabumi-agro',290000,'karung','Sukabumi'),('Pupuk NPK','pupuk-npk','pupuk','sukabumi-agro',15000,'kg','Sukabumi'),('Pupuk KCl','pupuk-kcl','pupuk','sukabumi-agro',14000,'kg','Sukabumi'),('Pupuk Organik','pupuk-organik','pupuk','tani-makmur',35000,'karung','Bogor'),
('Sprayer Punggung 16 L','sprayer','alat-pertanian','sukabumi-agro',275000,'unit','Sukabumi'),('Cangkul','cangkul','alat-pertanian','sukabumi-agro',85000,'unit','Sukabumi'),('Sekop','sekop','alat-pertanian','tani-makmur',65000,'unit','Bogor'),('Selang Irigasi 50 m','selang-irigasi','alat-pertanian','tani-makmur',180000,'roll','Bogor'),
('Mesin Pompa Air','mesin-pompa','mesin-pertanian','sukabumi-agro',1450000,'unit','Sukabumi'),('Tepung Jagung','olahan-jagung','produk-olahan','cianjur-jaya',18000,'kg','Cianjur'),('Keripik Singkong','olahan-singkong','produk-olahan','cianjur-jaya',22000,'pack','Cianjur'),('Mulsa Plastik','mulsa-plastik','lainnya','tani-makmur',350000,'roll','Bogor'))
insert into products(seller_id,category_id,name,slug,description,price,stock,unit,location,sold_count,rating)
select s.id,c.id,p.n,p.s,'Produk dummy '||p.n||' untuk demo TaniMart.',p.pr,50,p.u,p.l,(random()*200)::int,round((3.5+random()*1.5)::numeric,1) from p join categories c on c.slug=p.c join stores s on s.slug=p.st;
